import { Charger, EV } from './types';

export const chargers: Charger[] = [
  // Pune
  {
    id: 'CZ-001',
    name: 'Koregaon Park Plaza, Pune',
    status: 'Available',
    lat: 18.5362,
    lng: 73.9079,
    queue: [],
  },
  {
    id: 'CZ-002',
    name: 'Phoenix Marketcity, Pune',
    status: 'Occupied',
    lat: 18.5621,
    lng: 73.9167,
    currentUser: { id: '2', name: 'Priya' },
    currentVehicle: { model: 'Tesla Model 3', batteryPercentage: 45 },
    kwhReserved: 40,
    startTime: new Date(new Date().getTime() - 15 * 60000), // 15 mins ago
    estimatedEndTime: new Date(new Date().getTime() + 15 * 60000), // 15 mins from now
    queue: [
      { user: { id: '3', name: 'Rohan' }, joinTime: new Date(new Date().getTime() - 10 * 60000) },
    ],
  },
  {
    id: 'CZ-003',
    name: 'Westend Mall, Pune',
    status: 'Available',
    lat: 18.5084,
    lng: 73.8098,
    queue: [],
  },
  {
    id: 'CZ-004',
    name: 'Amanora Mall, Pune',
    status: 'Occupied',
    lat: 18.5244,
    lng: 73.9357,
    currentUser: { id: '4', name: 'Sameer' },
    currentVehicle: { model: 'MG ZS EV', batteryPercentage: 30 },
    kwhReserved: 35,
    startTime: new Date(new Date().getTime() - 10 * 60000),
    estimatedEndTime: new Date(new Date().getTime() + 35 * 60000),
    queue: [
       { user: { id: '5', name: 'Anjali' }, joinTime: new Date(new Date().getTime() - 5 * 60000) },
    ],
  },
  {
    id: 'CZ-005',
    name: 'Seasons Mall, Pune',
    status: 'Available',
    lat: 18.5258,
    lng: 73.9363,
    queue: [],
  },
  {
    id: 'CZ-006',
    name: 'Elpro City Square, Pune',
    status: 'Occupied',
    lat: 18.6220,
    lng: 73.8143,
    currentUser: { id: '6', name: 'Vikram' },
    currentVehicle: { model: 'Hyundai Kona Electric', batteryPercentage: 60 },
    kwhReserved: 25,
    startTime: new Date(new Date().getTime() - 20 * 60000),
    estimatedEndTime: new Date(new Date().getTime() + 25 * 60000),
    queue: [],
  },
  {
    id: 'CZ-007',
    name: 'Kumar Pacific Mall, Pune',
    status: 'Available',
    lat: 18.4988,
    lng: 73.8767,
    queue: [],
  },
  {
    id: 'CZ-008',
    name: 'SGS Magnum Mall, Pune',
    status: 'Available',
    lat: 18.5204,
    lng: 73.8567,
    queue: [],
  },
  // Mumbai
  {
    id: 'CZ-M01',
    name: 'Palladium Mall, Mumbai',
    status: 'Available',
    lat: 19.0042,
    lng: 72.8255,
    queue: [],
  },
  {
    id: 'CZ-M02',
    name: 'Jio World Drive, Mumbai',
    status: 'Occupied',
    lat: 19.0669,
    lng: 72.8621,
    currentUser: { id: '7', name: 'Alia' },
    currentVehicle: { model: 'Audi e-tron', batteryPercentage: 55 },
    kwhReserved: 50,
    startTime: new Date(new Date().getTime() - 25 * 60000),
    estimatedEndTime: new Date(new Date().getTime() + 40 * 60000),
    queue: [
      { user: { id: '8', name: 'Varun' }, joinTime: new Date(new Date().getTime() - 12 * 60000) },
    ],
  },
  // Delhi-NCR
  {
    id: 'CZ-D01',
    name: 'Select Citywalk, Delhi',
    status: 'Available',
    lat: 28.5284,
    lng: 77.2195,
    queue: [],
  },
  {
    id: 'CZ-D02',
    name: 'DLF CyberHub, Gurugram',
    status: 'Available',
    lat: 28.4947,
    lng: 77.0883,
    queue: [],
  },
  // Bangalore
  {
    id: 'CZ-B01',
    name: 'UB City, Bangalore',
    status: 'Occupied',
    lat: 12.9719,
    lng: 77.5937,
    currentUser: { id: '9', name: 'Deepika' },
    currentVehicle: { model: 'Jaguar I-PACE', batteryPercentage: 20 },
    kwhReserved: 70,
    startTime: new Date(new Date().getTime() - 5 * 60000),
    estimatedEndTime: new Date(new Date().getTime() + 60 * 60000),
    queue: [],
  },
  {
    id: 'CZ-B02',
    name: 'Orion Mall, Bangalore',
    status: 'Available',
    lat: 13.0102,
    lng: 77.5549,
    queue: [],
  },
  // Chennai
  {
    id: 'CZ-C01',
    name: 'Express Avenue, Chennai',
    status: 'Available',
    lat: 13.0604,
    lng: 80.2635,
    queue: [],
  },
  {
    id: 'CZ-C02',
    name: 'Phoenix Marketcity, Chennai',
    status: 'Occupied',
    lat: 12.9908,
    lng: 80.2177,
    currentUser: { id: '10', name: 'Suriya' },
    currentVehicle: { model: 'BYD Atto 3', batteryPercentage: 70 },
    kwhReserved: 15,
    startTime: new Date(new Date().getTime() - 30 * 60000),
    estimatedEndTime: new Date(new Date().getTime() + 10 * 60000),
    queue: [
      { user: { id: '11', name: 'Trisha' }, joinTime: new Date(new Date().getTime() - 15 * 60000) },
      { user: { id: '12', name: 'Vijay' }, joinTime: new Date(new Date().getTime() - 5 * 60000) },
    ],
  },
  // Kolkata
  {
    id: 'CZ-K01',
    name: 'South City Mall, Kolkata',
    status: 'Available',
    lat: 22.4984,
    lng: 88.3653,
    queue: [],
  },
  // Hyderabad
  {
    id: 'CZ-H01',
    name: 'Inorbit Mall, Hyderabad',
    status: 'Occupied',
    lat: 17.4262,
    lng: 78.3845,
    currentUser: { id: '13', name: 'Prabhas' },
    currentVehicle: { model: 'Kia EV6', batteryPercentage: 40 },
    kwhReserved: 45,
    startTime: new Date(new Date().getTime() - 18 * 60000),
    estimatedEndTime: new Date(new Date().getTime() + 30 * 60000),
    queue: [],
  },
  // Ahmedabad
  {
    id: 'CZ-A01',
    name: 'Ahmedabad One Mall, Ahmedabad',
    status: 'Available',
    lat: 23.0279,
    lng: 72.5284,
    queue: [],
  },
  // Jaipur
  {
    id: 'CZ-J01',
    name: 'World Trade Park, Jaipur',
    status: 'Available',
    lat: 26.8523,
    lng: 75.8055,
    queue: [],
  },
  // Lucknow
  {
    id: 'CZ-L01',
    name: 'Phoenix Palassio, Lucknow',
    status: 'Occupied',
    lat: 26.8049,
    lng: 81.0016,
    currentUser: { id: '14', name: 'Kriti' },
    currentVehicle: { model: 'Tata Nexon EV', batteryPercentage: 25 },
    kwhReserved: 22,
    startTime: new Date(new Date().getTime() - 8 * 60000),
    estimatedEndTime: new Date(new Date().getTime() + 45 * 60000),
    queue: [
      { user: { id: '15', name: 'Ayushmann' }, joinTime: new Date(new Date().getTime() - 2 * 60000) },
    ],
  },
];

export const evs: EV[] = [
    { model: 'Tata Nexon EV', batteryCapacity: 30.2 },
    { model: 'Tata Tigor EV', batteryCapacity: 26 },
    { model: 'Tata Punch EV', batteryCapacity: 25 },
    { model: 'MG ZS EV', batteryCapacity: 50.3 },
    { model: 'Hyundai Kona Electric', batteryCapacity: 39.2 },
    { model: 'Hyundai Ioniq 5', batteryCapacity: 72.6 },
    { model: 'Kia EV6', batteryCapacity: 77.4 },
    { model: 'BYD Atto 3', batteryCapacity: 60.48 },
    { model: 'BYD E6', batteryCapacity: 71.7 },
    { model: 'Mahindra XUV400', batteryCapacity: 39.4 },
    { model: 'Volvo XC40 Recharge', batteryCapacity: 78 },
    { model: 'Mercedes-Benz EQC', batteryCapacity: 80 },
    { model: 'BMW iX', batteryCapacity: 76.6 },
    { model: 'Audi e-tron', batteryCapacity: 95 },
    { model: 'Jaguar I-PACE', batteryCapacity: 90 },
    { model: 'Porsche Taycan', batteryCapacity: 93.4 },
    { model: 'Tesla Model 3', batteryCapacity: 75 },
    { model: 'Tesla Model Y', batteryCapacity: 82 },
];
